### ISSUE TITLE
Trying to POST creations e.g. BodyTemp, Condition, Sars etc. causes error

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge#71]
## Steps to reproduce ## 

1. Set up database using:
"docker run --name fhirdb -e POSTGRES_PASSWORD=fhir_bridge -e POSTGRES_USER=fhir_bridge -d -p 9999:5432 postgres"
2. create config/application.yml with the following values:

```yaml
ehrbase:
  address: localhost
  port: 8080
  path: /ehrbase/rest/openehr/v1/
spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/fhir_bridge
    username: fhir_bridge
    password: fhir_bridge
```

3. Use Insomnia to POST body temperature
4. displays error

## Actual result ##

```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Resource Patient/07f602e0-579e-4fe3-95af-381728bf0d49 not found, specified in path: Observation.subject.where(resolve() is Patient)"
    }
  ]
}
```
## Expected result ##

Success of Posting Body temperature

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings
